export  const testReducerConstants = {
  TEST: "TEST",
  END_TEST: "END_TEST"
};
// conversation action/reducer constants //
export const conversationConstants = {
  FETCH_CONVERSATIONS: "FETCH_CONVERSATIONS",
  REQUEST_CONVERSATIONS: "REQUEST_CONVERSATIONS",
  UPDATE_CONVERSATIONS: "UPDATE_CONVERSATIONS",
  OPEN_CONVERSATION: "OPEN_CONVERSATION",
  CLOSE_CONVERSATION: "CLOSE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  CONVERSATIONS_ERROR: "CONVERSATIONS_ERROR"
};
// messages action/reducer constants //
export const messagesConstants = {
  REQUEST_MESSAGES: "REQUEST_MESSAGES",
  UPDATE_MESSAGES: "UPDATE_MESSAGES",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  SEND_MESSAGE: "SEND_MESSAGE",
  MESSAGES_ERROR: "MESSAGES_ERROR"
};