export  const testReducerConstants = {
  TEST: "TEST",
  END_TEST: "END_TEST"
};
export const conversationConstants = {
  OPEN_CONVERSATION: "OPEN_CONVERSATION",
  CLOSE_CONVERSATION: "CLOSE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  CONVERSATIONS_ERROR: "CONVERSATIONS_ERROR"
};

export const messagesConstants = {
  DELETE_MESSAGE: "DELETE_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  SEND_MESSAGE: "SEND_MESSAGE",
  MESSAGES_ERROR: "MESSAGES_ERROR"
};